"""empty message

Revision ID: 36853fd24e23
Revises: 3a41c9c78eb9
Create Date: 2021-02-02 15:13:37.209759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36853fd24e23'
down_revision = '3a41c9c78eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_user_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_user_fkey', 'message', 'user', ['user'], ['id'])
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###
