"""empty message

Revision ID: 3a41c9c78eb9
Revises: edf6c14432c4
Create Date: 2021-02-02 14:56:56.302121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a41c9c78eb9'
down_revision = 'edf6c14432c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('session_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_session_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'room_session', ['session_id'], ['id'])
    op.drop_column('message', 'session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('session', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_session_fkey', 'message', 'room_session', ['session'], ['id'])
    op.drop_column('message', 'session_id')
    # ### end Alembic commands ###
