"""empty message

Revision ID: c7430f587fd5
Revises: 77cd2c2ef271
Create Date: 2021-01-19 11:29:43.025050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7430f587fd5'
down_revision = '77cd2c2ef271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_id')
    # ### end Alembic commands ###
