"""empty message

Revision ID: edf6c14432c4
Revises: 70544f781011
Create Date: 2021-02-02 05:50:34.638004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf6c14432c4'
down_revision = '70544f781011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_session_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('room_session_user1_fkey', 'room_session', type_='foreignkey')
    op.drop_constraint('room_session_user2_fkey', 'room_session', type_='foreignkey')
    op.drop_column('room_session', 'user2')
    op.drop_column('room_session', 'user1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_session', sa.Column('user1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('room_session', sa.Column('user2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('room_session_user2_fkey', 'room_session', 'user', ['user2'], ['id'])
    op.create_foreign_key('room_session_user1_fkey', 'room_session', 'user', ['user1'], ['id'])
    op.drop_table('room_session_user')
    # ### end Alembic commands ###
